spring:
    datasource:
        url: jdbc:h2:~/dashboardGL2;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    jpa:
        hibernate:
            ddl-auto:  create-drop
        show-sql: true
    h2:
      console:
        enabled: true
        path: /h2-console
server:
  port: 8089
  servlet:
    context-path: /api/v1
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
