spring:
    datasource:
        url: jdbc:h2:./dashboardGL2;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    jpa:
        hibernate:
            ddl-auto:  update
        show-sql: false

    h2:
      console:
        enabled: true
        path: /h2-console
        
server:
  port: 8089
  servlet:
    context-path: /api/v1

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 259200000